<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="App_Data\StringTheory.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Update="App_Data\PDFStandards.PDF">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="App_Data\TemplateIndex\segments_2">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="App_Data\TemplateIndex\_0.cfs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="App_Data\umbraco.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </None>
    <None Update="App_Data\TemplateIndex\segments.gen">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Content Include="App_Data\VS2010CSharp.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Update="App_Data\UmbracoContour.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Examine.Core\Examine.Core.csproj" />
    <ProjectReference Include="..\Examine.Host\Examine.csproj" />
    <ProjectReference Include="..\Examine.Lucene\Examine.Lucene.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="App_Data\media.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Lucene.Net.Spatial" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="Nunit3TestAdapter" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="DataServices\TestDataService.cs" />
    <Compile Remove="DataServices\TestLogService.cs" />
    <Compile Remove="Search\MultiIndexSearch.cs" />
  </ItemGroup>
</Project>
