# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # This builds all sln files, this could be updated to target what you want to build
  solution: '**/*.sln'
  # Typically none of these should be changed!
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publishDir: '$(build.artifactStagingDirectory)\_Publish'
  cloneDir: '$(build.artifactStagingDirectory)\_UmbracoCloud'
  zipDir: '$(build.artifactStagingDirectory)\_Zip'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $UsernameEncoded = [System.Web.HttpUtility]::UrlEncode("$(gitUsername)")
      $PasswordEncoded = [System.Web.HttpUtility]::UrlEncode("$(gitPassword)")
      $currentRemoteUri = New-Object System.Uri $(gitAddress)
      $newRemoteUrlBuilder = New-Object System.UriBuilder($currentRemoteUri)
      $newRemoteUrlBuilder.UserName = $UsernameEncoded 
      $newRemoteUrlBuilder.Password = $PasswordEncoded
      $gitAuthenticatedUrl = $newRemoteUrlBuilder.ToString()
      Write-Host "Cloning Umbraco Cloud repository..."
      git clone $gitAuthenticatedUrl
      Write-Host "Copying Build output to the Umbraco Cloud repository..."
