<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <!-- Used to test Nuget targeted benchmarks -->
    <LocalBuild>true</LocalBuild>
    <ExaminePackageVersion Condition="'$(SciVersion)' == ''">3.0.1</ExaminePackageVersion>
    <DefineConstants Condition="$(LocalBuild) != 'false'">$(DefineConstants);LocalBuild</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="$(LocalBuild) != 'false'">
    <ProjectReference Include="..\Examine.Host\Examine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Moq" />
    <PackageReference Include="BenchmarkDotNet" />
    <!-- Will be imported when running different Nuget targeted benchmarks -->
    <PackageReference Condition="$(LocalBuild) == 'false'" Include="Examine" Version="$(ExaminePackageVersion)" />
  </ItemGroup>

</Project>
